# records/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PatientViewSet, DoctorViewSet, PatientDoctorMappingCreateDestroy, PatientDoctorMappingList

# Use DefaultRouter for standard CRUD operations
router = DefaultRouter()
router.register(r'patients', PatientViewSet, basename='patient')
router.register(r'doctors', DoctorViewSet, basename='doctor')

urlpatterns = [
    # Include the routes generated by the router (e.g., /api/patients/, /api/doctors/1/)
    path('', include(router.urls)), 
    
    # 1. MAPPING ASSIGNMENT (POST) and DELETE (via PK)
    path('mappings/', PatientDoctorMappingCreateDestroy.as_view(), name='mapping_create'),
    path('mappings/<int:pk>/', PatientDoctorMappingCreateDestroy.as_view(), name='mapping_delete'),
    
    # 2. MAPPING RETRIEVAL (List all or list by specific patient)
    path('mappings/list/', PatientDoctorMappingList.as_view(), name='mapping_list_all'),
    path('mappings/<int:patient_id>/doctors/', PatientDoctorMappingList.as_view(), name='mapping_list_by_patient'),
]