# Generated by Django 5.1.7 on 2025-12-12 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdoctormapping",
            name="assigned_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patientdoctormapping",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_patients",
                to="records.doctor",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="patientdoctormapping",
            unique_together={("patient", "doctor")},
        ),
    ]
